# Generated by Django 3.1.7 on 2021-03-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=3000)),
                ('slug', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=30)),
            ],
        ),
    ]
