# Generated by Django 3.1.7 on 2021-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('massege', models.CharField(max_length=400)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
